# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos7"

  config.vm.hostname = "joelei"
  # config.ssh.username = "vagrant"
  # config.ssh.password = "vagrant"
  # config.ssh.insert_key = true

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "C:/", "/mnt/C", owner: "root", group: "root", mount_options: ["dmode=755,fmode=644"]
  config.vm.synced_folder "D:/", "/mnt/D", owner: "root", group: "root", mount_options: ["dmode=755,fmode=644"]
  config.vm.synced_folder "E:/", "/mnt/E", owner: "root", group: "root", mount_options: ["dmode=755,fmode=644"]
  config.vm.synced_folder "F:/", "/mnt/F", owner: "root", group: "root", mount_options: ["dmode=755,fmode=644"]
  config.vm.synced_folder "G:/", "/mnt/G", owner: "root", group: "root", mount_options: ["dmode=755,fmode=644"]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end

  config.vm.provision "shell", path: "https://raw.githubusercontent.com/ifooth/vagrant/master/centos7/bootstrap.sh"

end
